services:
  postgres:
    image: postgres:10.20
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: eccube_db
    networks:
      - backend
